### Get posts
GET http://localhost:3001

### Add new post

POST http://localhost:3001/new HTTP/1.1
Content-Type: application/json

{
    "menu_name": "Menu1_by Post method", 
    "menu_description": "Some quick example text to  and make up the bulk of the card content.",
    "price": "Price 10 € ",
    "image_name": "menucard6.png"
}


### Delete post

DELETE http://localhost:3001/delete/73



### login with valid creditials
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "username":"userthree",
    "email":"user3@gmail.com",
    "password": "user3"
}



### user resistation
POST http://localhost:3001/user/register
Content-Type: application/json

{
    "username":"userfour",
    "email":"user4@gmail.com",
    "password": "user4"
}

### comment get method
GET http://localhost:3001/comment

### comment post method
POST http://localhost:3001/comment/new HTTP/1.1
Content-Type: application/json

{
    "comment_text": "This is a comment2, for Nice product "
}