### Get posts
GET http://localhost:3001

### Add new post

POST http://localhost:3001/new HTTP/1.1
Content-Type: application/json

{
    "menu_name": "Menu1_by Post method", 
    "menu_description": "Some quick example text to  and make up the bulk of the card content.",
    "price": "Price 10 € ",
    "image_path": "Images/menucard1.jpg"
}


### Delete post

DELETE http://localhost:3001/delete/18